### ISSUE TITLE
internal/docker-push: multiple tags

### ISSUE THREAD

**Issue by JeanMertz** [wercker/support#147] opened 2015-10-19 09:10 UTC
It would be nice if `tag` accepted an array of tags, making that step push two different tags to the registry.

Specifically, we'd like to tag our images with the Git ref, but that makes it difficult to use the same image as a `service` in another application using Wercker, because we'd have to update its tag every time the service is updated.

Instead, I'd like to push both "latest" and the Git ref, and have the services reference latest.

(note that this is still not ideal, as latest is not always the version you want to work against, so maybe you have a better solution to this?)

**Comment by nhumrich** [comment] 2015-10-21 22:36
I am currently working around this by using two steps.

    - internal/docker-push:
            repository: $REPO
            tag: $TAG
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD
        - internal/docker-push:
            repository: $REPO
            tag: latest
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD

**Comment by hatchan** [comment] 2015-10-22 08:57
@JeanMertz This is something which definitely seems handy. 

You can do the `docker-push` in a separate deploy target, this allows you to do manual deploy as well as automatic deploys. In an automatic deploy use the git ref as the tag, and in the manual deploy we deploy to a channel such as `alpha`, `beta`, `production`. Then only deploy to the channels when you think it is possible to do so, then make the containers depend on them use a channel, instead of latest or a git ref.

@nhumrich Thanks for providing a workaround

**Comment by MaikuMori** [comment] 2015-12-22 11:04
Any update on this? Seems like quick thing to fix. Is there opensource project where I can fix this?

The workaround kinda works, but it will upload twice and the containers technically are not identical (correct me if I'm wrong).

**Comment by MaikuMori** [comment] 2016-02-03 07:36
So I dag into newly release CLI code and tested in a project and it seems like this issue has been fixed.

**Comment by ernoaapa** [comment] 2016-03-22 13:48
Yeah I can confirm that you can now define multiple tags separated with comma. Eg. `tag: latest,$WERCKER_GIT_BRANCH,$WERCKER_GIT_COMMIT`

**Comment by nhumrich** [comment] 2016-06-10 20:51
multiple tags doesnt seem to work with workflows 
```
Error interacting with this repository: invalid reference format
```

**Comment by hatchan** [comment] 2016-06-13 07:46
@nhumrich I have just tested it with workflows, and I couldn't reproduce it. Can you share your docker-push section from your wercker.yml?

**Comment by nhumrich** [comment] 2016-06-14 19:23
I think I might have had another issue. Its working now. Sorry for the confusion.

**Comment by hatchan** [comment] 2016-06-17 08:49
as mentioned by @ernoaapa, this is now working. Closing this issue

**Closed by hatchan** 2016-06-17 08:49 UTC
Labels: enhancement
