### ISSUE TITLE
aborting a build spins forever

### ISSUE THREAD

**Issue by tal-moshayov** [wercker/support#45] opened 2015-06-10 12:57 UTC
Hi, build #d6c67fd failed at the "store" phase (which is weird). I pressed rebuild and now it's in zombie land. It appears running in the feed view yet as aborted in the single build view.

**Comment by Tonnu** [comment] 2015-06-10 13:19
Hi Tal, could you pass me the wercker build ID? I'll look into what's happening.

**Comment by tal-moshayov** [comment] 2015-06-10 19:24
55782ca1bc00eeab440e0162

**Comment by Tonnu** [comment] 2015-07-06 16:00
Hi Tal,

Sorry for getting back to you so late. This is an issue we've seen cropping up every now and then and we are investigating it's root cause. The only fix I can offer you is to trigger a new build. If you don't want to push new commits I recommend you look into the API, which allows you to trigger builds on existing codebases. See this page for more info: http://devcenter.wercker.com/api/endpoints/builds.html

Hope that is of some help to you!

Closing this for now.

**Closed by Tonnu** 2015-07-06 16:00 UTC
